export const APPOINTMENT_TYPES = {
  INITIAL_CONSULTATION: 'INITIAL_CONSULTATION',
  DEVELOPMENT_ASSESSMENT: 'DEVELOPMENT_ASSESSMENT'
};

export const APPOINTMENT_TYPE_LABELS = {
  [APPOINTMENT_TYPES.INITIAL_CONSULTATION]: 'Initial Consultation',
  [APPOINTMENT_TYPES.DEVELOPMENT_ASSESSMENT]: 'Development Assessment'
};

export default APPOINTMENT_TYPES;
